In [1]:
import pandas as pd

import sqlite3
from sqlite3 import Error

In [23]:
SWISS = pd.read_csv("USCHF.csv")
JAP = pd.read_csv("USJP.csv")
EUR = pd.read_csv("USEU.csv")
BRIT = pd.read_csv("USGB.csv")

In [24]:
SWISS.columns =['month','av-USD-CHF','min-USD-CHF','max-USD-CHF','nb-days']
JAP.columns =['month','av-USD-JPY','min-USD-JPY','max-USD-JPY','nb-days']
EUR.columns =['month','av-USD-EUR','min-USD-EUR','max-USD-EUR','nb-days']
BRIT.columns =['month','av-USD-GBP','min-USD-GBP','max-USD-GBP','nb-days']

In [25]:
SWISS['month']=SWISS['month'].str.replace('/','-')
new = SWISS['month'].str.split("-", n = 1, expand = True)
SWISS["Month"]= new[0] 
SWISS["Year"]= new[1] 
SWISS.drop(columns =["month"], inplace = True) 

SWISS['date'] = SWISS["Year"].map(str) + "-" + SWISS["Month"].map(str)
SWISS.drop(columns =["Month","Year"], inplace = True) 
SWISS

     av-USD-CHF  min-USD-CHF  max-USD-CHF  nb-days     date
0      1.000912     0.991857     1.009502       22  2018-11
1      0.993871     0.983457     1.007157       23  2018-10
2      0.968041     0.954843     0.977540       20   2018-9
3      0.988282     0.968243     0.997401       23   2018-8
4      0.994563     0.987730     1.005239       22   2018-7
5      0.990080     0.981159     0.998189       21   2018-6
6      0.997212     0.985212     1.005209       22   2018-5
7      0.968596     0.953968     0.990886       20   2018-4
8      0.947183     0.935023     0.956010       21   2018-3
9      0.934801     0.924118     0.943180       20   2018-2
10     0.961141     0.933017     0.982819       22   2018-1
11     0.987615     0.975736     0.996764       19  2017-12
12     0.991688     0.980165     1.002411       22  2017-11
13     0.982152     0.970623     1.002327       22  2017-10
14     0.962726     0.945688     0.975300       21   2017-9
15     0.965696     0.945053     0.974039       23   2017-8
16     0.960783     0.946041     0.968619       21   2017-7
17     0.968370     0.957764     0.974747       22   2017-6
18     0.986275     0.970471     1.008471       22   2017-5
19     1.000409     0.990942     1.009832       18   2017-4
20     1.002132     0.983837     1.014975       23   2017-3
21     1.001645     0.989082     1.012271       20   2017-2
22     1.009432     0.991911     1.030525       22   2017-1
23     1.019767     1.008456     1.031166       21  2016-12
24     0.996461     0.971243     1.016970       22  2016-11
25     0.987420     0.971698     0.997792       21  2016-10
26     0.973849     0.966448     0.984927       22   2016-9
27     0.970561     0.958149     0.984280       23   2016-8
28     0.981779     0.972277     0.994268       21   2016-7
29     0.970200     0.954957     0.990676       22   2016-6
..          ...          ...          ...      ...      ...
754    4.285208     4.284611     4.285482       22   1956-1
755    4.284980     4.284712     4.285351       22  1955-12
756    4.285036     4.284393     4.285700       22  1955-11
757    4.285745     4.285162     4.286136       21  1955-10
758    4.285356     4.284074     4.285830       22   1955-9
759    4.285983     4.285075     4.287080       23   1955-8
760    4.285768     4.285046     4.286208       21   1955-7
761    4.285243     4.284755     4.285932       22   1955-6
762    4.285486     4.284915     4.285947       22   1955-5
763    4.285935     4.285016     4.287868       21   1955-4
764    4.286195     4.284477     4.287216       23   1955-3
765    4.288045     4.286881     4.290237       20   1955-2
766    4.286763     4.285948     4.287348       21   1955-1
767    4.285437     4.284840     4.286822       23  1954-12
768    4.286634     4.285408     4.287771       22  1954-11
769    4.288282     4.287115     4.290049       21  1954-10
770    4.287316     4.286327     4.288444       22   1954-9
771    4.288032     4.286531     4.289363       22   1954-8
772    4.288533     4.286152     4.290342       22   1954-7
773    4.285661     4.284840     4.286589       22   1954-6
774    4.286391     4.285714     4.287464       21   1954-5
775    4.289465     4.287027     4.290749       22   1954-4
776    4.290425     4.289654     4.291407       23   1954-3
777    4.289074     4.287464     4.290749       20   1954-2
778    4.291365     4.290311     4.294039       21   1954-1
779    4.295487     4.288778     4.303720       23  1953-12
780    4.300283     4.292723     4.306809       21  1953-11
781    4.290471     4.287902     4.294039       22  1953-10
782    4.286878     4.286152     4.288778       22   1953-9
783    4.285701     4.282655     4.287027       16   1953-8

[784 rows x 5 columns]

In [26]:
JAP['month']=JAP['month'].str.replace('/','-')
new = JAP['month'].str.split("-", n = 1, expand = True)
JAP["Month"]= new[0] 
JAP["Year"]= new[1] 
JAP.drop(columns =["month"], inplace = True) 

JAP['date'] = JAP["Year"].map(str) + "-" + JAP["Month"].map(str)
JAP.drop(columns =["Month","Year"], inplace = True) 
JAP

     av-USD-JPY  min-USD-JPY  max-USD-JPY  nb-days     date
0    113.303265   112.371946   113.950804       22  2018-11
1    112.866090   111.846991   114.162754       23  2018-10
2    111.960762   110.839432   113.363856       20   2018-9
3    111.004118   110.261708   111.841655       23   2018-8
4    111.447072   110.450420   113.030721       22   2018-7
5    110.058908   109.431712   110.687940       21   2018-6
6    109.693159   108.838362   111.267965       22   2018-5
7    107.658473   106.239844   109.379916       20   2018-4
8    106.076950   105.086668   106.891259       21   2018-3
9    107.948161   106.177792   109.863344       20   2018-2
10   110.886321   108.670799   113.283520       22   2018-1
11   112.906978   112.143522   113.496515       19  2017-12
12   112.797776   111.019076   114.193046       22  2017-11
13   112.935803   111.827501   114.192159       22  2017-10
14   110.731514   107.379768   112.937569       21   2017-9
15   109.887463   108.615538   110.858693       23   2017-8
16   112.495383   110.599471   114.300745       21   2017-7
17   110.941917   109.362231   112.669763       22   2017-6
18   112.236762   110.566987   113.923586       22   2017-5
19   110.318991   108.837296   111.451153       18   2017-4
20   112.957353   110.138672   115.425231       23   2017-3
21   112.913112   111.945617   114.495500       20   2017-2
22   115.080029   113.347061   118.199326       22   2017-1
23   116.109858   113.888367   118.191398       21  2016-12
24   108.345950   102.983864   113.286319       22  2016-11
25   103.826998   101.370595   105.383629       21  2016-10
26   101.871757   100.285205   103.705365       22   2016-9
27   101.227281    99.814077   103.314768       23   2016-8
28   104.128204   100.424571   106.537728       21   2016-7
29   105.478207   101.654846   109.244675       22   2016-6
..          ...          ...          ...      ...      ...
677  360.000000   360.000000   360.000000       21   1962-6
678  360.000000   360.000000   360.000000       23   1962-5
679  360.000000   360.000000   360.000000       21   1962-4
680  360.000000   360.000000   360.000000       22   1962-3
681  360.000000   360.000000   360.000000       20   1962-2
682  360.000000   360.000000   360.000000       23   1962-1
683  360.000000   360.000000   360.000000       21  1961-12
684  360.000000   360.000000   360.000000       22  1961-11
685  360.000000   360.000000   360.000000       22  1961-10
686  360.000000   360.000000   360.000000       21   1961-9
687  360.000000   360.000000   360.000000       23   1961-8
688  360.000000   360.000000   360.000000       21   1961-7
689  360.000000   360.000000   360.000000       22   1961-6
690  360.000000   360.000000   360.000000       23   1961-5
691  360.000000   360.000000   360.000000       20   1961-4
692  360.000000   360.000000   360.000000       23   1961-3
693  360.000000   360.000000   360.000000       20   1961-2
694  360.000000   360.000000   360.000000       22   1961-1
695  360.000000   360.000000   360.000000       22  1960-12
696  360.000000   360.000000   360.000000       22  1960-11
697  360.000000   360.000000   360.000000       21  1960-10
698  360.000000   360.000000   360.000000       22   1960-9
699  360.000000   360.000000   360.000000       23   1960-8
700  360.000000   360.000000   360.000000       21   1960-7
701  360.000000   360.000000   360.000000       22   1960-6
702  360.000000   360.000000   360.000000       22   1960-5
703  360.000000   360.000000   360.000000       21   1960-4
704  360.000000   360.000000   360.000000       23   1960-3
705  360.000000   360.000000   360.000000       21   1960-2
706  360.000000   360.000000   360.000000       21   1960-1

[707 rows x 5 columns]

In [27]:
EUR['month']=EUR['month'].str.replace('/','-')
new = EUR['month'].str.split("-", n = 1, expand = True)
EUR["Month"]= new[0] 
EUR["Year"]= new[1] 
EUR.drop(columns =["month"], inplace = True) 

EUR['date'] = EUR["Year"].map(str) + "-" + EUR["Month"].map(str)
EUR.drop(columns =["Month","Year"], inplace = True) 
EUR

     av-USD-EUR  min-USD-EUR  max-USD-EUR  nb-days     date
0      0.879773     0.870549     0.888021       22  2018-11
1      0.870816     0.861623     0.883548       23  2018-10
2      0.857763     0.849113     0.864902       20   2018-9
3      0.865963     0.853971     0.883314       23   2018-8
4      0.855759     0.848248     0.862962       22   2018-7
5      0.856336     0.844880     0.867002       21   2018-6
6      0.846676     0.832848     0.865202       22   2018-5
7      0.814625     0.807233     0.828500       20   2018-4
8      0.810642     0.805088     0.821625       21   2018-3
9      0.809896     0.800448     0.818733       20   2018-2
10     0.819851     0.802761     0.838082       22   2018-1
11     0.844888     0.833820     0.852079       19  2017-12
12     0.852009     0.836680     0.864902       22  2017-11
13     0.850666     0.843455     0.861698       22  2017-10
14     0.839346     0.829187     0.851716       21   2017-9
15     0.846969     0.830013     0.853971       23   2017-8
16     0.868839     0.852588     0.882690       21   2017-7
17     0.890555     0.876194     0.897102       22   2017-6
18     0.904505     0.889442     0.920810       22   2017-5
19     0.932703     0.914913     0.945358       18   2017-4
20     0.936016     0.918358     0.951113       23   2017-3
21     0.939664     0.925241     0.951203       20   2017-2
22     0.942206     0.929800     0.962927       22   2017-1
23     0.948636     0.929195     0.964878       21  2016-12
24     0.926326     0.901307     0.948047       22  2016-11
25     0.907036     0.889996     0.919794       21  2016-10
26     0.891907     0.885269     0.897183       22   2016-9
27     0.891965     0.881912     0.902690       23   2016-8
28     0.903484     0.896298     0.910581       21   2016-7
29     0.890646     0.878040     0.909256       22   2016-6
..          ...          ...          ...      ...      ...
754    0.958285     0.957764     0.958797       22   1956-1
755    0.957653     0.956371     0.958944       22  1955-12
756    0.956937     0.956244     0.957834       22  1955-11
757    0.957459     0.955577     0.958268       21  1955-10
758    0.955169     0.954301     0.955881       22   1955-9
759    0.954647     0.954344     0.955230       23   1955-8
760    0.955716     0.954398     0.956472       21   1955-7
761    0.955690     0.954665     0.956178       22   1955-6
762    0.954174     0.953454     0.954727       22   1955-5
763    0.952932     0.950662     0.954239       21   1955-4
764    0.949733     0.948634     0.950611       23   1955-3
765    0.949738     0.948837     0.950146       20   1955-2
766    0.950340     0.949432     0.951013       21   1955-1
767    0.951197     0.950437     0.951695       23  1954-12
768    0.951520     0.950666     0.951954       22  1954-11
769    0.951935     0.951157     0.952817       21  1954-10
770    0.951812     0.950756     0.952299       22   1954-9
771    0.953965     0.952427     0.954913       22   1954-8
772    0.954288     0.953669     0.954840       22   1954-7
773    0.953999     0.952603     0.954755       22   1954-6
774    0.954579     0.953937     0.955176       21   1954-5
775    0.955046     0.954641     0.955345       22   1954-4
776    0.955169     0.954727     0.955388       23   1954-3
777    0.954769     0.954296     0.955263       20   1954-2
778    0.955023     0.954203     0.955732       21   1954-1
779    0.955114     0.954246     0.955735       23  1953-12
780    0.954651     0.954229     0.954971       21  1953-11
781    0.955238     0.954682     0.955608       22  1953-10
782    0.953999     0.952072     0.955828       22   1953-9
783    0.953595     0.952074     0.955221       16   1953-8

[784 rows x 5 columns]

In [28]:
BRIT['month']=BRIT['month'].str.replace('/','-')
new = BRIT['month'].str.split("-", n = 1, expand = True)
BRIT["Month"]= new[0]
BRIT["Year"]= new[1] 
BRIT.drop(columns =["month"], inplace = True) 

BRIT['date'] = BRIT["Year"].map(str) + "-" + BRIT["Month"].map(str)
BRIT.drop(columns =["Month","Year"], inplace = True) 
BRIT

     av-USD-GBP  min-USD-GBP  max-USD-GBP  nb-days     date
0      0.775233     0.760886     0.784118       22  2018-11
1      0.768700     0.755853     0.785236       23  2018-10
2      0.765824     0.752740     0.779900       20   2018-9
3      0.776637     0.761286     0.787298       23   2018-8
4      0.759279     0.749385     0.770608       22   2018-7
5      0.752594     0.744534     0.764223       21   2018-6
6      0.742731     0.733239     0.753963       22   2018-5
7      0.710468     0.698228     0.728206       20   2018-4
8      0.715687     0.702989     0.727303       21   2018-3
9      0.715919     0.702464     0.723882       20   2018-2
10     0.724229     0.701523     0.741242       22   2018-1
11     0.745730     0.739359     0.749020       19  2017-12
12     0.756511     0.742552     0.763710       22  2017-11
13     0.757681     0.751953     0.764799       22  2017-10
14     0.750922     0.735961     0.772441       21   2017-9
15     0.771778     0.755981     0.780854       23   2017-8
16     0.769892     0.760886     0.776705       21   2017-7
17     0.781223     0.770531     0.790095       22   2017-6
18     0.773732     0.767032     0.778760       22   2017-5
19     0.791172     0.772855     0.806721       18   2017-4
20     0.810213     0.793489     0.823657       23   2017-3
21     0.801255     0.791640     0.808712       20   2017-2
22     0.811219     0.794219     0.828847       22   2017-1
23     0.801046     0.784516     0.818460       21  2016-12
24     0.804643     0.789921     0.817896       22  2016-11
25     0.810832     0.777127     0.823155       21  2016-10
26     0.760146     0.747246     0.773308       22   2016-9
27     0.762791     0.749196     0.775286       23   2016-8
28     0.759878     0.746715     0.770621       21   2016-7
29     0.704188     0.672535     0.758320       22   2016-6
..          ...          ...          ...      ...      ...
754    0.359317     0.359055     0.359689       22   1956-1
755    0.359122     0.358435     0.359851       22  1955-12
756    0.358918     0.358496     0.359567       22  1955-11
757    0.359551     0.359374     0.359781       21  1955-10
758    0.360414     0.359619     0.361112       22   1955-9
759    0.360369     0.360003     0.360794       23   1955-8
760    0.360562     0.359635     0.360942       21   1955-7
761    0.359601     0.358719     0.360313       22   1955-6
762    0.358275     0.357585     0.358947       22   1955-5
763    0.356921     0.356404     0.357394       21   1955-4
764    0.356345     0.355762     0.356660       23   1955-3
765    0.357010     0.356055     0.357185       20   1955-2
766    0.357366     0.356843     0.357704       21   1955-1
767    0.357050     0.356870     0.357171       23  1954-12
768    0.356745     0.356600     0.356965       22  1954-11
769    0.357149     0.356638     0.357603       21  1954-10
770    0.357655     0.357230     0.358007       22   1954-9
771    0.358099     0.357852     0.358313       22   1954-8
772    0.358113     0.357654     0.358475       22   1954-7
773    0.357592     0.357264     0.357767       22   1954-6
774    0.357231     0.356597     0.357599       21   1954-5
775    0.357612     0.357143     0.358056       22   1954-4
776    0.358524     0.358117     0.358729       23   1954-3
777    0.358905     0.358637     0.359066       20   1954-2
778    0.359334     0.358852     0.359620       21   1954-1
779    0.359078     0.358423     0.359681       23  1953-12
780    0.358607     0.358362     0.358913       21  1953-11
781    0.359068     0.358882     0.359343       22  1953-10
782    0.359286     0.358668     0.359651       22   1953-9
783    0.358971     0.358545     0.359097       16   1953-8

[784 rows x 5 columns]

In [29]:
def create_connection(db_file):
    """ create a database connection to a SQLite database """
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
    finally:
        conn.close()
 
if __name__ == '__main__':
    create_connection("currency.sqlite")

2.6.0

In [30]:
conn = sqlite3.connect("currency.sqlite")
cur = conn.cursor()
EUR.to_sql(name = "EUR", con = conn)
query = "SELECT * FROM EUR;"
df = pd.read_sql_query(query,conn)
df

     index  av-USD-EUR  min-USD-EUR  max-USD-EUR  nb-days     date
0        0    0.879773     0.870549     0.888021       22  2018-11
1        1    0.870816     0.861623     0.883548       23  2018-10
2        2    0.857763     0.849113     0.864902       20   2018-9
3        3    0.865963     0.853971     0.883314       23   2018-8
4        4    0.855759     0.848248     0.862962       22   2018-7
5        5    0.856336     0.844880     0.867002       21   2018-6
6        6    0.846676     0.832848     0.865202       22   2018-5
7        7    0.814625     0.807233     0.828500       20   2018-4
8        8    0.810642     0.805088     0.821625       21   2018-3
9        9    0.809896     0.800448     0.818733       20   2018-2
10      10    0.819851     0.802761     0.838082       22   2018-1
11      11    0.844888     0.833820     0.852079       19  2017-12
12      12    0.852009     0.836680     0.864902       22  2017-11
13      13    0.850666     0.843455     0.861698       22  2017-10
14      14    0.839346     0.829187     0.851716       21   2017-9
15      15    0.846969     0.830013     0.853971       23   2017-8
16      16    0.868839     0.852588     0.882690       21   2017-7
17      17    0.890555     0.876194     0.897102       22   2017-6
18      18    0.904505     0.889442     0.920810       22   2017-5
19      19    0.932703     0.914913     0.945358       18   2017-4
20      20    0.936016     0.918358     0.951113       23   2017-3
21      21    0.939664     0.925241     0.951203       20   2017-2
22      22    0.942206     0.929800     0.962927       22   2017-1
23      23    0.948636     0.929195     0.964878       21  2016-12
24      24    0.926326     0.901307     0.948047       22  2016-11
25      25    0.907036     0.889996     0.919794       21  2016-10
26      26    0.891907     0.885269     0.897183       22   2016-9
27      27    0.891965     0.881912     0.902690       23   2016-8
28      28    0.903484     0.896298     0.910581       21   2016-7
29      29    0.890646     0.878040     0.909256       22   2016-6
..     ...         ...          ...          ...      ...      ...
754    754    0.958285     0.957764     0.958797       22   1956-1
755    755    0.957653     0.956371     0.958944       22  1955-12
756    756    0.956937     0.956244     0.957834       22  1955-11
757    757    0.957459     0.955577     0.958268       21  1955-10
758    758    0.955169     0.954301     0.955881       22   1955-9
759    759    0.954647     0.954344     0.955230       23   1955-8
760    760    0.955716     0.954398     0.956472       21   1955-7
761    761    0.955690     0.954665     0.956178       22   1955-6
762    762    0.954174     0.953454     0.954727       22   1955-5
763    763    0.952932     0.950662     0.954239       21   1955-4
764    764    0.949733     0.948634     0.950611       23   1955-3
765    765    0.949738     0.948837     0.950146       20   1955-2
766    766    0.950340     0.949432     0.951013       21   1955-1
767    767    0.951197     0.950437     0.951695       23  1954-12
768    768    0.951520     0.950666     0.951954       22  1954-11
769    769    0.951935     0.951157     0.952817       21  1954-10
770    770    0.951812     0.950756     0.952299       22   1954-9
771    771    0.953965     0.952427     0.954913       22   1954-8
772    772    0.954288     0.953669     0.954840       22   1954-7
773    773    0.953999     0.952603     0.954755       22   1954-6
774    774    0.954579     0.953937     0.955176       21   1954-5
775    775    0.955046     0.954641     0.955345       22   1954-4
776    776    0.955169     0.954727     0.955388       23   1954-3
777    777    0.954769     0.954296     0.955263       20   1954-2
778    778    0.955023     0.954203     0.955732       21   1954-1
779    779    0.955114     0.954246     0.955735       23  1953-12
780    780    0.954651     0.954229     0.954971       21  1953-11
781    781    0.955238     0.954682     0.955608       22  1953-10
782    782    0.953999     0.952072     0.955828       22   1953-9
783    783    0.953595     0.952074     0.955221       16   1953-8

[784 rows x 6 columns]

In [31]:
conn = sqlite3.connect("currency.sqlite")
cur = conn.cursor()
SWISS.to_sql(name = "CHF", con = conn)
query = "SELECT * FROM CHF;"
df = pd.read_sql_query(query,conn)
df

     index  av-USD-CHF  min-USD-CHF  max-USD-CHF  nb-days     date
0        0    1.000912     0.991857     1.009502       22  2018-11
1        1    0.993871     0.983457     1.007157       23  2018-10
2        2    0.968041     0.954843     0.977540       20   2018-9
3        3    0.988282     0.968243     0.997401       23   2018-8
4        4    0.994563     0.987730     1.005239       22   2018-7
5        5    0.990080     0.981159     0.998189       21   2018-6
6        6    0.997212     0.985212     1.005209       22   2018-5
7        7    0.968596     0.953968     0.990886       20   2018-4
8        8    0.947183     0.935023     0.956010       21   2018-3
9        9    0.934801     0.924118     0.943180       20   2018-2
10      10    0.961141     0.933017     0.982819       22   2018-1
11      11    0.987615     0.975736     0.996764       19  2017-12
12      12    0.991688     0.980165     1.002411       22  2017-11
13      13    0.982152     0.970623     1.002327       22  2017-10
14      14    0.962726     0.945688     0.975300       21   2017-9
15      15    0.965696     0.945053     0.974039       23   2017-8
16      16    0.960783     0.946041     0.968619       21   2017-7
17      17    0.968370     0.957764     0.974747       22   2017-6
18      18    0.986275     0.970471     1.008471       22   2017-5
19      19    1.000409     0.990942     1.009832       18   2017-4
20      20    1.002132     0.983837     1.014975       23   2017-3
21      21    1.001645     0.989082     1.012271       20   2017-2
22      22    1.009432     0.991911     1.030525       22   2017-1
23      23    1.019767     1.008456     1.031166       21  2016-12
24      24    0.996461     0.971243     1.016970       22  2016-11
25      25    0.987420     0.971698     0.997792       21  2016-10
26      26    0.973849     0.966448     0.984927       22   2016-9
27      27    0.970561     0.958149     0.984280       23   2016-8
28      28    0.981779     0.972277     0.994268       21   2016-7
29      29    0.970200     0.954957     0.990676       22   2016-6
..     ...         ...          ...          ...      ...      ...
754    754    4.285208     4.284611     4.285482       22   1956-1
755    755    4.284980     4.284712     4.285351       22  1955-12
756    756    4.285036     4.284393     4.285700       22  1955-11
757    757    4.285745     4.285162     4.286136       21  1955-10
758    758    4.285356     4.284074     4.285830       22   1955-9
759    759    4.285983     4.285075     4.287080       23   1955-8
760    760    4.285768     4.285046     4.286208       21   1955-7
761    761    4.285243     4.284755     4.285932       22   1955-6
762    762    4.285486     4.284915     4.285947       22   1955-5
763    763    4.285935     4.285016     4.287868       21   1955-4
764    764    4.286195     4.284477     4.287216       23   1955-3
765    765    4.288045     4.286881     4.290237       20   1955-2
766    766    4.286763     4.285948     4.287348       21   1955-1
767    767    4.285437     4.284840     4.286822       23  1954-12
768    768    4.286634     4.285408     4.287771       22  1954-11
769    769    4.288282     4.287115     4.290049       21  1954-10
770    770    4.287316     4.286327     4.288444       22   1954-9
771    771    4.288032     4.286531     4.289363       22   1954-8
772    772    4.288533     4.286152     4.290342       22   1954-7
773    773    4.285661     4.284840     4.286589       22   1954-6
774    774    4.286391     4.285714     4.287464       21   1954-5
775    775    4.289465     4.287027     4.290749       22   1954-4
776    776    4.290425     4.289654     4.291407       23   1954-3
777    777    4.289074     4.287464     4.290749       20   1954-2
778    778    4.291365     4.290311     4.294039       21   1954-1
779    779    4.295487     4.288778     4.303720       23  1953-12
780    780    4.300283     4.292723     4.306809       21  1953-11
781    781    4.290471     4.287902     4.294039       22  1953-10
782    782    4.286878     4.286152     4.288778       22   1953-9
783    783    4.285701     4.282655     4.287027       16   1953-8

[784 rows x 6 columns]

In [32]:
conn = sqlite3.connect("currency.sqlite")
cur = conn.cursor()
JAP.to_sql(name = "JPY", con = conn)
query = "SELECT * FROM JPY;"
df = pd.read_sql_query(query,conn)
df

     index  av-USD-JPY  min-USD-JPY  max-USD-JPY  nb-days     date
0        0  113.303265   112.371946   113.950804       22  2018-11
1        1  112.866090   111.846991   114.162754       23  2018-10
2        2  111.960762   110.839432   113.363856       20   2018-9
3        3  111.004118   110.261708   111.841655       23   2018-8
4        4  111.447072   110.450420   113.030721       22   2018-7
5        5  110.058908   109.431712   110.687940       21   2018-6
6        6  109.693159   108.838362   111.267965       22   2018-5
7        7  107.658473   106.239844   109.379916       20   2018-4
8        8  106.076950   105.086668   106.891259       21   2018-3
9        9  107.948161   106.177792   109.863344       20   2018-2
10      10  110.886321   108.670799   113.283520       22   2018-1
11      11  112.906978   112.143522   113.496515       19  2017-12
12      12  112.797776   111.019076   114.193046       22  2017-11
13      13  112.935803   111.827501   114.192159       22  2017-10
14      14  110.731514   107.379768   112.937569       21   2017-9
15      15  109.887463   108.615538   110.858693       23   2017-8
16      16  112.495383   110.599471   114.300745       21   2017-7
17      17  110.941917   109.362231   112.669763       22   2017-6
18      18  112.236762   110.566987   113.923586       22   2017-5
19      19  110.318991   108.837296   111.451153       18   2017-4
20      20  112.957353   110.138672   115.425231       23   2017-3
21      21  112.913112   111.945617   114.495500       20   2017-2
22      22  115.080029   113.347061   118.199326       22   2017-1
23      23  116.109858   113.888367   118.191398       21  2016-12
24      24  108.345950   102.983864   113.286319       22  2016-11
25      25  103.826998   101.370595   105.383629       21  2016-10
26      26  101.871757   100.285205   103.705365       22   2016-9
27      27  101.227281    99.814077   103.314768       23   2016-8
28      28  104.128204   100.424571   106.537728       21   2016-7
29      29  105.478207   101.654846   109.244675       22   2016-6
..     ...         ...          ...          ...      ...      ...
677    677  360.000000   360.000000   360.000000       21   1962-6
678    678  360.000000   360.000000   360.000000       23   1962-5
679    679  360.000000   360.000000   360.000000       21   1962-4
680    680  360.000000   360.000000   360.000000       22   1962-3
681    681  360.000000   360.000000   360.000000       20   1962-2
682    682  360.000000   360.000000   360.000000       23   1962-1
683    683  360.000000   360.000000   360.000000       21  1961-12
684    684  360.000000   360.000000   360.000000       22  1961-11
685    685  360.000000   360.000000   360.000000       22  1961-10
686    686  360.000000   360.000000   360.000000       21   1961-9
687    687  360.000000   360.000000   360.000000       23   1961-8
688    688  360.000000   360.000000   360.000000       21   1961-7
689    689  360.000000   360.000000   360.000000       22   1961-6
690    690  360.000000   360.000000   360.000000       23   1961-5
691    691  360.000000   360.000000   360.000000       20   1961-4
692    692  360.000000   360.000000   360.000000       23   1961-3
693    693  360.000000   360.000000   360.000000       20   1961-2
694    694  360.000000   360.000000   360.000000       22   1961-1
695    695  360.000000   360.000000   360.000000       22  1960-12
696    696  360.000000   360.000000   360.000000       22  1960-11
697    697  360.000000   360.000000   360.000000       21  1960-10
698    698  360.000000   360.000000   360.000000       22   1960-9
699    699  360.000000   360.000000   360.000000       23   1960-8
700    700  360.000000   360.000000   360.000000       21   1960-7
701    701  360.000000   360.000000   360.000000       22   1960-6
702    702  360.000000   360.000000   360.000000       22   1960-5
703    703  360.000000   360.000000   360.000000       21   1960-4
704    704  360.000000   360.000000   360.000000       23   1960-3
705    705  360.000000   360.000000   360.000000       21   1960-2
706    706  360.000000   360.000000   360.000000       21   1960-1

[707 rows x 6 columns]

In [33]:
conn = sqlite3.connect("currency.sqlite")
cur = conn.cursor()
BRIT.to_sql(name = "GBP", con = conn)
query = "SELECT * FROM GBP;"
df = pd.read_sql_query(query,conn)
df

     index  av-USD-GBP  min-USD-GBP  max-USD-GBP  nb-days     date
0        0    0.775233     0.760886     0.784118       22  2018-11
1        1    0.768700     0.755853     0.785236       23  2018-10
2        2    0.765824     0.752740     0.779900       20   2018-9
3        3    0.776637     0.761286     0.787298       23   2018-8
4        4    0.759279     0.749385     0.770608       22   2018-7
5        5    0.752594     0.744534     0.764223       21   2018-6
6        6    0.742731     0.733239     0.753963       22   2018-5
7        7    0.710468     0.698228     0.728206       20   2018-4
8        8    0.715687     0.702989     0.727303       21   2018-3
9        9    0.715919     0.702464     0.723882       20   2018-2
10      10    0.724229     0.701523     0.741242       22   2018-1
11      11    0.745730     0.739359     0.749020       19  2017-12
12      12    0.756511     0.742552     0.763710       22  2017-11
13      13    0.757681     0.751953     0.764799       22  2017-10
14      14    0.750922     0.735961     0.772441       21   2017-9
15      15    0.771778     0.755981     0.780854       23   2017-8
16      16    0.769892     0.760886     0.776705       21   2017-7
17      17    0.781223     0.770531     0.790095       22   2017-6
18      18    0.773732     0.767032     0.778760       22   2017-5
19      19    0.791172     0.772855     0.806721       18   2017-4
20      20    0.810213     0.793489     0.823657       23   2017-3
21      21    0.801255     0.791640     0.808712       20   2017-2
22      22    0.811219     0.794219     0.828847       22   2017-1
23      23    0.801046     0.784516     0.818460       21  2016-12
24      24    0.804643     0.789921     0.817896       22  2016-11
25      25    0.810832     0.777127     0.823155       21  2016-10
26      26    0.760146     0.747246     0.773308       22   2016-9
27      27    0.762791     0.749196     0.775286       23   2016-8
28      28    0.759878     0.746715     0.770621       21   2016-7
29      29    0.704188     0.672535     0.758320       22   2016-6
..     ...         ...          ...          ...      ...      ...
754    754    0.359317     0.359055     0.359689       22   1956-1
755    755    0.359122     0.358435     0.359851       22  1955-12
756    756    0.358918     0.358496     0.359567       22  1955-11
757    757    0.359551     0.359374     0.359781       21  1955-10
758    758    0.360414     0.359619     0.361112       22   1955-9
759    759    0.360369     0.360003     0.360794       23   1955-8
760    760    0.360562     0.359635     0.360942       21   1955-7
761    761    0.359601     0.358719     0.360313       22   1955-6
762    762    0.358275     0.357585     0.358947       22   1955-5
763    763    0.356921     0.356404     0.357394       21   1955-4
764    764    0.356345     0.355762     0.356660       23   1955-3
765    765    0.357010     0.356055     0.357185       20   1955-2
766    766    0.357366     0.356843     0.357704       21   1955-1
767    767    0.357050     0.356870     0.357171       23  1954-12
768    768    0.356745     0.356600     0.356965       22  1954-11
769    769    0.357149     0.356638     0.357603       21  1954-10
770    770    0.357655     0.357230     0.358007       22   1954-9
771    771    0.358099     0.357852     0.358313       22   1954-8
772    772    0.358113     0.357654     0.358475       22   1954-7
773    773    0.357592     0.357264     0.357767       22   1954-6
774    774    0.357231     0.356597     0.357599       21   1954-5
775    775    0.357612     0.357143     0.358056       22   1954-4
776    776    0.358524     0.358117     0.358729       23   1954-3
777    777    0.358905     0.358637     0.359066       20   1954-2
778    778    0.359334     0.358852     0.359620       21   1954-1
779    779    0.359078     0.358423     0.359681       23  1953-12
780    780    0.358607     0.358362     0.358913       21  1953-11
781    781    0.359068     0.358882     0.359343       22  1953-10
782    782    0.359286     0.358668     0.359651       22   1953-9
783    783    0.358971     0.358545     0.359097       16   1953-8

[784 rows x 6 columns]

In [44]:
REC = pd.read_csv("recession.csv")
REC.drop(columns =["Unnamed: 0"], inplace = True)
new = REC['Date'].str.split("-", n = 2, expand = True)
REC["Month"]= new[1]
REC["Year"]= new[0]
REC.drop(columns =["Date"], inplace = True) 

REC['date'] = REC["Year"].map(str) + "-" + REC["Month"].map(str)
REC.drop(columns =["Month","Year"], inplace = True) 
REC

      Recession_Indicator     date
0                       1  1854-12
1                       0  1855-01
2                       0  1855-02
3                       0  1855-03
4                       0  1855-04
5                       0  1855-05
6                       0  1855-06
7                       0  1855-07
8                       0  1855-08
9                       0  1855-09
10                      0  1855-10
11                      0  1855-11
12                      0  1855-12
13                      0  1856-01
14                      0  1856-02
15                      0  1856-03
16                      0  1856-04
17                      0  1856-05
18                      0  1856-06
19                      0  1856-07
20                      0  1856-08
21                      0  1856-09
22                      0  1856-10
23                      0  1856-11
24                      0  1856-12
25                      0  1857-01
26                      0  1857-02
27                      0  1857-03
28                      0  1857-04
29                      0  1857-05
...                   ...      ...
1938                    0  2016-06
1939                    0  2016-07
1940                    0  2016-08
1941                    0  2016-09
1942                    0  2016-10
1943                    0  2016-11
1944                    0  2016-12
1945                    0  2017-01
1946                    0  2017-02
1947                    0  2017-03
1948                    0  2017-04
1949                    0  2017-05
1950                    0  2017-06
1951                    0  2017-07
1952                    0  2017-08
1953                    0  2017-09
1954                    0  2017-10
1955                    0  2017-11
1956                    0  2017-12
1957                    0  2018-01
1958                    0  2018-02
1959                    0  2018-03
1960                    0  2018-04
1961                    0  2018-05
1962                    0  2018-06
1963                    0  2018-07
1964                    0  2018-08
1965                    0  2018-09
1966                    0  2018-10
1967                    0  2018-11

[1968 rows x 2 columns]

In [47]:
conn = sqlite3.connect("currency.sqlite")
cur = conn.cursor()
REC.to_sql(name = "RInd", con = conn)
query = "SELECT * FROM RInd;"
df = pd.read_sql_query(query,conn)
df

      index  Recession_Indicator     date
0         0                    1  1854-12
1         1                    0  1855-01
2         2                    0  1855-02
3         3                    0  1855-03
4         4                    0  1855-04
5         5                    0  1855-05
6         6                    0  1855-06
7         7                    0  1855-07
8         8                    0  1855-08
9         9                    0  1855-09
10       10                    0  1855-10
11       11                    0  1855-11
12       12                    0  1855-12
13       13                    0  1856-01
14       14                    0  1856-02
15       15                    0  1856-03
16       16                    0  1856-04
17       17                    0  1856-05
18       18                    0  1856-06
19       19                    0  1856-07
20       20                    0  1856-08
21       21                    0  1856-09
22       22                    0  1856-10
23       23                    0  1856-11
24       24                    0  1856-12
25       25                    0  1857-01
26       26                    0  1857-02
27       27                    0  1857-03
28       28                    0  1857-04
29       29                    0  1857-05
...     ...                  ...      ...
1938   1938                    0  2016-06
1939   1939                    0  2016-07
1940   1940                    0  2016-08
1941   1941                    0  2016-09
1942   1942                    0  2016-10
1943   1943                    0  2016-11
1944   1944                    0  2016-12
1945   1945                    0  2017-01
1946   1946                    0  2017-02
1947   1947                    0  2017-03
1948   1948                    0  2017-04
1949   1949                    0  2017-05
1950   1950                    0  2017-06
1951   1951                    0  2017-07
1952   1952                    0  2017-08
1953   1953                    0  2017-09
1954   1954                    0  2017-10
1955   1955                    0  2017-11
1956   1956                    0  2017-12
1957   1957                    0  2018-01
1958   1958                    0  2018-02
1959   1959                    0  2018-03
1960   1960                    0  2018-04
1961   1961                    0  2018-05
1962   1962                    0  2018-06
1963   1963                    0  2018-07
1964   1964                    0  2018-08
1965   1965                    0  2018-09
1966   1966                    0  2018-10
1967   1967                    0  2018-11

[1968 rows x 3 columns]